trigger:
  - none
pool:
  vmImage: ubuntu-latest

stages:
  - stage: preBuild
    jobs:
      - job: test
        displayName: test
        steps:
          - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
            inputs:
              artifactsPayload: |
                {
                    "artifacts": [
                      {
                          "name": "sampletest",
                          "version": "1.$(Build.BuildId)",
                          "semanticVersion": "1.$(Build.BuildId).0",
                          "repositoryName": "adopipelineProject"
                      }
                    ]
                }
  - stage: Build
    jobs:
      - job: test
        displayName: test
        steps:
          - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
            inputs:
              artifactsPayload: |
                {
                    "artifacts": [
                      {
                          "name": "sampletestBuild",
                          "version": "1.$(Build.BuildId)",
                          "semanticVersion": "1.$(Build.BuildId).0",
                          "repositoryName": "adopipelineProject"
                      }
                    ]
                }
