trigger:
- none
pool:
  vmImage: ubuntu-latest
variables:
- group: Variable Group

stages:

  # - stage: Build
  #   jobs:
  #     - job: 'b1'
  #       steps:
  #       - task: PublishPipelineArtifact@1
  #         inputs:
  #           targetPath: '$(System.DefaultWorkingDirectory)'
  #           artifact: 'ADOBuildAndReleasePipelineCICD-Artifact'
  #           publishLocation: 'pipeline'

  - stage: Test
    jobs:
      - job: 't1'
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - task: ServiceNow-DevOps-Build-Sonar-Registration@1
          inputs:
            connectedServiceName: 'empnarendra1-adopipelineProject-ServiceNow DevOps Service Connection'
            sonarProjectKey: 'balu-sn-devops_First_repo'
            sonarInstanceUrl: 'http://sonarqube1.sndevops.xyz'

  # - stage: Deploy
  #   jobs:
  #     - job: 'd1'
  #       pool: server
  #       steps:       
  #          - task: ServiceNow-DevOps-Server-Change-Acceleration@1
  #            inputs:
  #              connectedServiceName: '$(ServiceNowConnection)'
  #              UpstreamJob: 't1'